### ISSUE TITLE
Store "credentials" for guest accessing the site

### ISSUE THREAD

**Issue by cshabsin** [cshabsin/conju#6]
A "current invitation" may be the right way to do this, given the old system's reliance on "invitation code" for identifying users, but we my want to investigate having a per-guest login instead. 

Does "Invitation code" convey write permissions for all Persons associated with the invitation? Even if we're using those Person records as our address book outside the context of the event?

There are some beginnings of notes on this in docs/schema.md. TODO(cshabsin): move those into comments into this issues so this thread contains all the relevant information and discussion.

**Comment by dscott617** [comment]
I think per-person login is a good idea, but I think we need to keep the ability to edit information for anyone in the group.  In the past most invitees have had one person fill out the form for everyone.  Plus, no matter what we do, someone will need to fill out the form for small children.  Which is maybe its own issue, because some children do have email addresses and their parents give them when they fill out the form.  Is a 12-year-old with their own email address allowed to rsvp for their party?  Do we need to restrict actions based on age?

I think the consequences if someone fills out the wrong information for someone in their party for the current year are small, it's easy to restrict it to the current year (to stay away from the acrimonious breakup case) and the inconvenience of requiring everyone to fill out their own form is large.

**Comment by cshabsin** [comment]
Maybe an invitation could have a per-guest boolean of whether that guest is an administrator of all members of the invitation?

**Comment by dscott617** [comment]
Probably not necessary to have a separate property; it's easy to identify adults.  If there's a birthdate, look for people older than [age].  If no birthday, is NeedBirthdate true?  That's how I've been marking kids without a birthdate, so we can prompt the adults to enter one.

**Comment by cshabsin** [comment]
This is done. LoginCode is a field on Person, and LoginGetter looks up Person from the code, as well as pulling the invitation from the current event.

Should probably separate out LoginGetter from InvitationGetter, now that I think of it.
